![logo_ironhack_blue 7](https://user-images.githubusercontent.com/23629340/40541063-a07a0a8a-601a-11e8-91b5-2f13e4e6b441.png)

# Lab | Tableau

### Learning Outcomes

Upon completion of this lab, you will be able to:

- Load and integrate datasets into Tableau for analysis.
- Differentiate between and appropriately assign measurements and dimensions within Tableau.
- Construct insightful barplots to compare categorical data.
- Design a treeplot to visualize hierarchical data.
- Synthesize cross tables to examine relationships between two categorical variables.
- Assemble a comprehensive dashboard that encapsulates multiple facets of the dataset.
- Save your Tableau workbook for future reference and sharing.

### Instructions

1. **Data Import**: Begin by loading the dataset `we_fn_use_c_marketing_customer_value_analysis.csv` available [here](https://raw.githubusercontent.com/data-bootcamp-v4/data/main/we_fn_use_c_marketing_customer_value_analysis.csv) into Tableau.

2. **Gender Barplot**: Create a barplot to visualize the distribution of customers by **Gender**.

3. **Employment and Gender Barplot**: Construct a barplot that represents the number of customers by **EmploymentStatus** segmented by **Gender**.

4. **Measurements vs. Dimensions**: Review the **Measurements** and **Dimensions** identified by Tableau. Adjust them if necessary to ensure they match your data structure and analysis needs.

5. **Gender Barplot Sheet**: Develop a sheet dedicated to displaying the barplot of customer counts by **Gender**.

6. **Employment and Gender Barplot Sheet**: Prepare a separate sheet to showcase the barplot of customer counts by **EmploymentStatus** and **Gender**.

7. **State Treeplot Sheet**: Create a sheet with a treeplot (also known as a treemap) illustrating the number of customers in each **State**.

8. **Marital Status and Gender Cross Table**: Generate a cross table that breaks down the customers by Marital status and Gender.

9. **Dashboard Assembly**: Compile all the created sheets into a single, interactive dashboard for an integrated view of the data insights.

10. **Save Your Work**: Preserve your Tableau workbook by saving it as `tableau-lab.tbwx`.

---
# Solved Lab | Tableau
---

In [ ]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
import seaborn as sns

plt.style.use('ggplot')
pd.set_option('display.max_columns', 200) # to display all columns in the dataframe

## **Instructions**
---
### 1. **Data Import**: 
Begin by loading the dataset `we_fn_use_c_marketing_customer_value_analysis.csv` available [here](https://raw.githubusercontent.com/data-bootcamp-v4/data/main/we_fn_use_c_marketing_customer_value_analysis.csv) into Tableau.


My steps:
- launch the tableau app
- click Text file
- Select the .csv file

In [1]:
import pandas as pd
df = pd.read_csv('we_fn_use_c_marketing_customer_value_analysis.csv')

In [5]:
display(df.head(10))

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,Location Code,Marital Status,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,Suburban,Married,69,32,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,Suburban,Single,94,13,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,Suburban,Married,108,18,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,Suburban,Married,106,18,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,2/3/11,Employed,M,43836,Rural,Single,73,12,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize
5,OC83172,Oregon,8256.297800,Yes,Basic,Bachelor,1/25/11,Employed,F,62902,Rural,Married,69,14,94,0,2,Personal Auto,Personal L3,Offer2,Web,159.383042,Two-Door Car,Medsize
6,XZ87318,Oregon,5380.898636,Yes,Basic,College,2/24/11,Employed,F,55350,Suburban,Married,67,0,13,0,9,Corporate Auto,Corporate L3,Offer1,Agent,321.600000,Four-Door Car,Medsize
7,CF85061,Arizona,7216.100311,No,Premium,Master,1/18/11,Unemployed,M,0,Urban,Single,101,0,68,0,4,Corporate Auto,Corporate L3,Offer1,Agent,363.029680,Four-Door Car,Medsize
8,DY87989,Oregon,24127.504020,Yes,Basic,Bachelor,1/26/11,Medical Leave,M,14072,Suburban,Divorced,71,13,3,0,2,Corporate Auto,Corporate L3,Offer1,Agent,511.200000,Four-Door Car,Medsize
9,BQ94931,Oregon,7388.178085,No,Extended,College,2/17/11,Employed,F,28812,Urban,Married,93,17,7,0,8,Special Auto,Special L2,Offer2,Branch,425.527834,Four-Door Car,Medsize

---
### 2. **Gender Barplot**: 
Create a barplot to visualize the distribution of customers by **Gender**.

In [6]:
df["Gender"].value_counts()

Gender
F    4658
M    4476
Name: count, dtype: int64

---
### 3. **Employment and Gender Barplot**: 
Construct a barplot that represents the number of customers by **EmploymentStatus** segmented by **Gender**.

In [13]:
df_gender_status = df[["Gender", "EmploymentStatus"]]
display(df_gender_status)

     Gender EmploymentStatus
0         F         Employed
1         F       Unemployed
2         F         Employed
3         M       Unemployed
4         M         Employed
...     ...              ...
9129      M         Employed
9130      F         Employed
9131      M       Unemployed
9132      M         Employed
9133      M       Unemployed

[9134 rows x 2 columns]

In [14]:
table = df.groupby(["Gender", "EmploymentStatus"]).size().unstack(fill_value=0)
table.columns.name = None
table.index.name = None

table

   Disabled  Employed  Medical Leave  Retired  Unemployed
F       244      2937            214      128        1135
M       161      2761            218      154        1182

---
### 4. **Measurements vs. Dimensions**: 
Review the **Measurements** and **Dimensions** identified by Tableau. 
Adjust them if necessary to ensure they match your data structure and analysis needs.

I checked :
- Gender is a Dimension
- Customers is a Count

---
### 5. **Gender Barplot Sheet**: 
Develop a sheet dedicated to displaying the barplot of customer counts by **Gender**.

I named the sheet as: Customers Gender Distribution

---
### 6. **Employment and Gender Barplot Sheet**: 
Prepare a separate sheet to showcase the barplot of customer counts by **EmploymentStatus** and **Gender**.

I named the sheet as: Customers Employment by Gender (bar plot)

---
### 7. **State Treeplot Sheet**: 
Create a sheet with a treeplot (also known as a treemap) illustrating the number of customers in each **State**.

In [19]:
display(df["State"].value_counts())

State
California    3150
Oregon        2601
Arizona       1703
Nevada         882
Washington     798
Name: count, dtype: int64

In [16]:
table = df.groupby(["Gender", "State"]).size().unstack(fill_value=0)
table.columns.name = None
table.index.name = None

table

   Arizona  California  Nevada  Oregon  Washington
F      875        1582     455    1334         412
M      828        1568     427    1267         386

I named the sheet as: Customers State Distribution

---
### 8. **Marital Status and Gender Cross Table**: 
Generate a cross table that breaks down the customers by Marital status and Gender.

In [15]:
table = df.groupby(["Gender", "Marital Status"]).size().unstack(fill_value=0)
table.columns.name = None
table.index.name = None

table

   Divorced  Married  Single
F       709     2779    1170
M       660     2519    1297

---
### 9. **Dashboard Assembly**: 
Compile all the created sheets into a single, interactive dashboard for an integrated view of the data insights.

---
### 10. **Save Your Work**: 
Preserve your Tableau workbook by saving it as `tableau-lab.tbwx`.